version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - app-network

#  frontend:
#    build: ./frontend
#    ports:
#      - "4200:80"
#    depends_on:
#      - backend
#    networks:
#      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge